server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: company-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/company/**
            -
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
            -
        - id: analytics-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/analytics/**
            -
        - id: Collaboration-Request
          uri: http://localhost:8083
          predicates:
            - Path=/api/Collaboration-Request/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka