import React, { useEffect, useState } from "react";
import {
  Box,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from "@mui/material";
import axios from "axios";

/**
 * TopSellingProduct Component
 * 
 * This component fetches and displays the top-selling products in a table format.
 * It uses React's `useState` and `useEffect` hooks to manage state and side effects.
 * 
 * @component
 * 
 * @example
 * // Example usage:
 * <TopSellingProduct />
 * 
 * @returns {JSX.Element} A styled box containing a table of top-selling products.
 * 
 * @remarks
 * - The component fetches data from the API endpoint: 
 *   "https://localhost:8080/api/analytics/topsellingproducts".
 * - The data is expected to be an array of objects, where each object represents a product.
 * 
 * @typedef {Object} Product
 * @property {string} name - The name of the product.
 * @property {number} price - The price of the product.
 * @property {number} quantity - The quantity sold.
 * @property {number} amount - The total amount generated by the product.
 * 
 * @example
 * // Sample API response:
 * [
 *   {
 *     "name": "Product A",
 *     "price": 100,
 *     "quantity": 5,
 *     "amount": 500
 *   },
 *   {
 *     "name": "Product B",
 *     "price": 200,
 *     "quantity": 3,
 *     "amount": 600
 *   }
 * ]
 * 
 * @throws {Error} Logs an error to the console if the API request fails.
 */
export default function TopSellingProduct() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const fetchProducts = async () => {
      const user = localStorage.getItem("company");
      if (user) {
        const user = JSON.parse(user);
      try {
        const response = await axios.get(
          "https://localhost:8080/api/analytics/topsellingproducts/" + user.companyId
        );
        setProducts(response.data);
      } catch (error) {
        console.error("Error fetching top selling products:", error);
      }}
    };

    fetchProducts();
  }, []);

  return (
    <Box
      sx={{
        margin: 3,
        bgcolor: "white",
        borderRadius: 2,
        padding: 3,
        height: "95%",
      }}
    >
      <Typography variant="h6" fontWeight={"bold"} sx={{ mx: 3 }}>
        Top selling products
      </Typography>
      <TableContainer>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell sx={{ fontWeight: "bolder" }}>Name</TableCell>
              <TableCell sx={{ fontWeight: "bolder" }}>Price</TableCell>
              <TableCell sx={{ fontWeight: "bolder" }}>Quantity</TableCell>
              <TableCell sx={{ fontWeight: "bolder" }}>Amount</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {products.map((product, id) => (
              <TableRow key={id}>
                <TableCell>{product.name}</TableCell>
                <TableCell>{product.price}</TableCell>
                <TableCell>{product.quantity}</TableCell>
                <TableCell>{product.amount}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Box>
  );
}
